package iam

type AutoGenerated struct {
	Auth Auth `json:"auth,omitempty"`
}

type Auth struct {
	Identity Identity `json:"identity,omitempty"`
	Scope    Scope    `json:"scope,omitempty"`
}
type Identity struct {
	Methods     []string     `json:"methods,omitempty"`
	HwAccessKey *HwAccessKey `json:"hw_access_key,omitempty"`
	Password    Password     `json:"password,omitempty"`
}
type Password struct {
	User User `json:"user,omitempty"`
}
type User struct {
	Name     string `json:"name,omitempty"`
	Password string `json:"password,omitempty"`
	Domain   Domain `json:"domain,omitempty"`
}
type Scope struct {
	Project *Project `json:"project,omitempty"`
	Domain  Domain   `json:"domain,omitempty"`
}
type Project struct {
	ID   string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
type Domain struct {
	Name string `json:"name,omitempty"`
}
type HwAccessKey struct {
	Access Access `json:"access,omitempty"`
}
type Access struct {
	Key string `json:"key,omitempty"`
}
